name: emotion_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_riverpod: ^2.4.3
  kartal: ^3.4.4
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  animated_emoji: ^3.0.0

  shimmer: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
